name: Push Client to Test Repo
on:
  push:
    branches: [ sandbox ]
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        ref: sandbox

    - name: Set up remotes to Backend Test Repo
      run: |
        git config --global user.email "watchpartyappmain@gmail.com"
        git config --global user.name "watchpartyappmain"
        echo Config Succeeded
        git remote add testing https://github.com/watchpartyappmain/watchparty-frontend-test.git
        echo Remote Added Successfully
        git fetch --all
        git filter-branch --prune-empty --subdirectory-filter WatchParty/client sandbox
        echo Fetched and prunned server

    - name: Delete heroku-depoy on remote repo
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.personal_github_token }}
        REPOSITORY: 'watchpartyappmain/watchparty-frontend-test'
        INPUT_BRANCH: 'deploy-heroku'
      run: |
        remote_repo="https://watchpartymainapp:${INPUT_GITHUB_TOKEN}@github.com/${REPOSITORY}.git"
        git push "${remote_repo}" --delete ${INPUT_BRANCH} --force;

    - name: Checkout new branch
      run: |
        git checkout -b deploy-heroku sandbox
        echo Checkedout new deploy-heroku branch

    - name: Push to Client Test Repo
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.personal_github_token }}
        REPOSITORY: 'watchpartyappmain/watchparty-frontend-test'
        INPUT_BRANCH: 'heroku-deploy'
      run: |
        remote_repo="https://watchpartymainapp:${INPUT_GITHUB_TOKEN}@github.com/${REPOSITORY}.git"
        git push "${remote_repo}" HEAD:${INPUT_BRANCH} --follow-tags --force;
